# Generated by Django 2.0.2 on 2018-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='occo_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occo_noi', models.PositiveIntegerField()),
                ('system_line', models.CharField(max_length=50)),
                ('occo_date', models.DateTimeField()),
            ],
        ),
    ]
