# Generated by Django 2.0.2 on 2018-05-30 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chainage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('end_chainage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dicipline', models.CharField(max_length=100)),
                ('work_info', models.CharField(max_length=255)),
                ('additional_details', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='occo_details',
            name='occo_date',
        ),
        migrations.AddField(
            model_name='occo_details',
            name='occo_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occo_details',
            name='occo_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occo_details',
            name='occo_type',
            field=models.CharField(default='Delivery', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occo_details',
            name='rail_system',
            field=models.CharField(default='Western', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occo_details',
            name='system_line',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='work_details',
            name='occo_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_wall.occo_details'),
        ),
    ]
