# Generated by Django 2.0.2 on 2018-05-30 08:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('the_wall', '0002_auto_20180530_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='occo_details',
            new_name='Occupation',
        ),
        migrations.RenameModel(
            old_name='work_details',
            new_name='Work',
        ),
    ]
