# Generated by Django 2.0.2 on 2018-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0002_auto_20180621_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['occupation_start_date'], 'permissions': (('view_occo', 'View Occupation'),)},
        ),
    ]
