# Generated by Django 2.0.2 on 2018-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0003_auto_20180530_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='rail_system',
            new_name='rail_area',
        ),
    ]
