# Generated by Django 2.0.2 on 2018-06-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0004_auto_20180530_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='dicipline',
        ),
        migrations.AddField(
            model_name='work',
            name='discipline',
            field=models.CharField(default=1, help_text='Enter the discipline e.g. Civil', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occo_type',
            field=models.CharField(help_text='Enter the Occupation Type e.g. BLU', max_length=50),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='rail_area',
            field=models.CharField(help_text='Enter the Rail Area Type e.g. North/North-East', max_length=50),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='system_line',
            field=models.CharField(help_text='Enter the System Line e.g. Sunbury to Bendigo.', max_length=100),
        ),
    ]
