# Generated by Django 2.0.2 on 2018-06-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0005_auto_20180601_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='occo_end_date',
            new_name='occupation_end_date',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='occo_noi',
            new_name='occupation_noi',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='occo_start_date',
            new_name='occupation_start_date',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='occo_type',
            new_name='occupation_type',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='occo_details',
            new_name='occupation_details',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_info',
            new_name='work_information',
        ),
    ]
