# Generated by Django 2.0.2 on 2018-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0006_auto_20180601_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='additional_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='discipline',
            field=models.CharField(choices=[('c', 'Civil'), ('t', 'Track'), ('f', 'Facilities'), ('s', 'Signals')], help_text='Enter the discipline e.g. Civil', max_length=100),
        ),
    ]
