# Generated by Django 2.0.2 on 2018-06-01 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0007_auto_20180601_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='additional_details',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
