# Generated by Django 2.0.2 on 2018-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0008_auto_20180601_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='rail_area',
            field=models.CharField(choices=[('w', 'Western Region'), ('n', 'North/North-East Region'), ('c', 'Central & Eastern Region')], help_text='Enter the Rail Area Type e.g. North/North-East', max_length=50),
        ),
    ]
