# Generated by Django 2.0.2 on 2018-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0010_auto_20180601_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='discipline',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Track', 'Track'), ('Facilities', 'Facilities'), ('Signals', 'Signals')], help_text='Enter the discipline e.g. Civil', max_length=100),
        ),
    ]
