# Generated by Django 2.0.2 on 2018-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0011_auto_20180601_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='rail_area',
            field=models.CharField(choices=[('Western Region', 'Western Region'), ('North/North-East Region', 'North/North-East Region'), ('Central & Eastern Region', 'Central & Eastern Region')], help_text='Enter the Rail Area Type e.g. North/North-East', max_length=50),
        ),
    ]
