# Generated by Django 2.0.2 on 2018-06-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0013_auto_20180605_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='works_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='works_start_date',
            field=models.DateField(),
        ),
    ]
